server:
  port: 8082

campanhaService:
  uri: http://localhost:8081/campanhas

spring:
  application:
    name: socio-torcedor-core
    version: 1.0.0
  jackson:
    serialization:
      write_dates_as_timestamps: false
    